#!/bin/bash
# Session End Hook - Save session summary
# Receives JSON input via stdin from Claude Code hooks

set -euo pipefail

# Create sessions directory if it doesn't exist
mkdir -p ~/.claude/sessions

# Get current date for filename
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M%S)
SESSION_FILE=~/.claude/sessions/${DATE}-${TIME}-summary.md

# Parse input (session info from Claude Code)
INPUT=$(cat)

# Extract session info if available
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"' 2>/dev/null || echo "unknown")

# Create session summary
cat > "$SESSION_FILE" << EOF
# Session Summary

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Session ID:** $SESSION_ID

## Session Ended

This session has ended. Review the conversation history for details.

---
*Generated by session-end hook*
EOF

exit 0
